"""baseline: postgres 16 schema for wodbuster worker

Revision ID: 6af804dc63e6
Revises:
Create Date: 2026-07-02 14:43:22.940387

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6af804dc63e6'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('cookie_expiring', 'cookie_invalid', 'heartbeat_anomaly', name='alert_kind_enum'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_emitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_emitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operator_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_operator_id'), 'alert', ['operator_id'], unique=False)
    op.create_index('uq_alert_open_operator_kind', 'alert', ['operator_id', 'kind'], unique=True, postgresql_where=sa.text('closed_at IS NULL'))
    op.create_table('cookie_credential',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('cookie_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('cookie_nonce', sa.LargeBinary(), nullable=False),
    sa.Column('pasted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('projected_ttl_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_probe_status', sa.Enum('valid', 'rejected', 'unknown', name='cookie_probe_status_enum'), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operator_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operator_id', name='uq_cookie_credential_operator')
    )
    op.create_table('federated_identity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('microsoft', 'github', 'google', name='provider_enum'), nullable=False),
    sa.Column('subject_id', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('refresh_token_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('refresh_token_nonce', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operator_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'subject_id', name='uq_federated_identity_provider_subject')
    )
    op.create_index(op.f('ix_federated_identity_operator_id'), 'federated_identity', ['operator_id'], unique=False)
    op.create_table('notification_outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('telegram', 'banner', name='notification_kind_enum'), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enqueued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operator_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_outbox_operator_id'), 'notification_outbox', ['operator_id'], unique=False)
    op.create_table('scheduler_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('window_offset_hours', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operator_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduler_rule_operator_id'), 'scheduler_rule', ['operator_id'], unique=False)
    op.create_table('vacation_window',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operator_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacation_window_operator_id'), 'vacation_window', ['operator_id'], unique=False)
    op.create_table('booking_outcome',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('target_class', sa.String(length=100), nullable=False),
    sa.Column('target_slot', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('terminal_status', sa.Enum('granted', 'full', 'cookie_invalid', 'class_not_visible', 'upstream_unavailable', 'cancelled', name='booking_terminal_status_enum'), nullable=False),
    sa.Column('granted_fallback_index', sa.Integer(), nullable=True),
    sa.Column('response_payload', sa.Text(), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operator_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['scheduler_rule.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_outcome_operator_id'), 'booking_outcome', ['operator_id'], unique=False)
    op.create_table('class_preference',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('class_type', sa.String(length=100), nullable=False),
    sa.Column('target_time_slot', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['scheduler_rule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'order_index', name='uq_class_preference_rule_order')
    )
    op.create_index(op.f('ix_class_preference_rule_id'), 'class_preference', ['rule_id'], unique=False)
    op.create_table('heartbeat_reading',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('probed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('result', sa.Enum('valid', 'rejected', 'unknown', name='heartbeat_result_enum'), nullable=False),
    sa.Column('projected_ttl_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operator_id'], ['operator_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heartbeat_reading_operator_id'), 'heartbeat_reading', ['operator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heartbeat_reading_operator_id'), table_name='heartbeat_reading')
    op.drop_table('heartbeat_reading')
    op.drop_index(op.f('ix_class_preference_rule_id'), table_name='class_preference')
    op.drop_table('class_preference')
    op.drop_index(op.f('ix_booking_outcome_operator_id'), table_name='booking_outcome')
    op.drop_table('booking_outcome')
    op.drop_index(op.f('ix_vacation_window_operator_id'), table_name='vacation_window')
    op.drop_table('vacation_window')
    op.drop_index(op.f('ix_scheduler_rule_operator_id'), table_name='scheduler_rule')
    op.drop_table('scheduler_rule')
    op.drop_index(op.f('ix_notification_outbox_operator_id'), table_name='notification_outbox')
    op.drop_table('notification_outbox')
    op.drop_index(op.f('ix_federated_identity_operator_id'), table_name='federated_identity')
    op.drop_table('federated_identity')
    op.drop_table('cookie_credential')
    op.drop_index('uq_alert_open_operator_kind', table_name='alert', postgresql_where=sa.text('closed_at IS NULL'))
    op.drop_index(op.f('ix_alert_operator_id'), table_name='alert')
    op.drop_table('alert')
    op.drop_table('operator_profile')
    # ### end Alembic commands ###

    # Alembic autogenerate does not drop native enum types alongside their
    # owning columns. Without these explicit drops, a downgrade followed by
    # an upgrade fails with `DuplicateObject: type "<name>_enum" already exists`.
    bind = op.get_bind()
    for enum_name in (
        'alert_kind_enum',
        'booking_terminal_status_enum',
        'cookie_probe_status_enum',
        'heartbeat_result_enum',
        'notification_kind_enum',
        'provider_enum',
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
