"""Baseline schema for the WodBuster worker.

Creates every table declared in ``wodbuster_worker.persistence.models``.
Autogenerated by Alembic against SQLAlchemy metadata and lightly
hand-groomed: removed the "please adjust!" comments, dropped ``Union``
in favour of ``|`` for revision identifier annotations, and left
``batch_alter_table`` wrappers in place so the partial unique index on
``alert.(operator_id, kind)`` renders correctly under SQLite.

Revision ID: c7808dfff47d
Revises:
Create Date: 2026-07-01
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7808dfff47d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "operator_profile",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("telegram_chat_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "alert",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operator_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "cookie_expiring",
                "cookie_invalid",
                "heartbeat_anomaly",
                name="alert_kind_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("payload", sa.Text(), nullable=True),
        sa.Column(
            "first_emitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "last_emitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["operator_id"], ["operator_profile.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("alert", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_alert_operator_id"), ["operator_id"], unique=False
        )
        batch_op.create_index(
            "uq_alert_open_operator_kind",
            ["operator_id", "kind"],
            unique=True,
            sqlite_where=sa.text("closed_at IS NULL"),
        )

    op.create_table(
        "cookie_credential",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operator_id", sa.Integer(), nullable=False),
        sa.Column("cookie_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("cookie_nonce", sa.LargeBinary(), nullable=False),
        sa.Column(
            "pasted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("last_validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("projected_ttl_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_probe_status",
            sa.Enum(
                "valid",
                "rejected",
                "unknown",
                name="cookie_probe_status_enum",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["operator_id"], ["operator_profile.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("operator_id", name="uq_cookie_credential_operator"),
    )
    op.create_table(
        "federated_identity",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operator_id", sa.Integer(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("microsoft", "github", "google", name="provider_enum", native_enum=False),
            nullable=False,
        ),
        sa.Column("subject_id", sa.String(length=256), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("refresh_token_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("refresh_token_nonce", sa.LargeBinary(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["operator_id"], ["operator_profile.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "subject_id", name="uq_federated_identity_provider_subject"
        ),
    )
    with op.batch_alter_table("federated_identity", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_federated_identity_operator_id"),
            ["operator_id"],
            unique=False,
        )

    op.create_table(
        "notification_outbox",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operator_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("telegram", "banner", name="notification_kind_enum", native_enum=False),
            nullable=False,
        ),
        sa.Column("target", sa.String(length=200), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column(
            "enqueued_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.ForeignKeyConstraint(["operator_id"], ["operator_profile.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notification_outbox", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notification_outbox_operator_id"),
            ["operator_id"],
            unique=False,
        )

    op.create_table(
        "scheduler_rule",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operator_id", sa.Integer(), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("window_offset_hours", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["operator_id"], ["operator_profile.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scheduler_rule", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scheduler_rule_operator_id"), ["operator_id"], unique=False
        )

    op.create_table(
        "vacation_window",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operator_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["operator_id"], ["operator_profile.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("vacation_window", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_vacation_window_operator_id"), ["operator_id"], unique=False
        )

    op.create_table(
        "booking_outcome",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operator_id", sa.Integer(), nullable=False),
        sa.Column("rule_id", sa.Integer(), nullable=True),
        sa.Column("target_class", sa.String(length=100), nullable=False),
        sa.Column("target_slot", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "attempted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "terminal_status",
            sa.Enum(
                "granted",
                "full",
                "cookie_invalid",
                "class_not_visible",
                "upstream_unavailable",
                "cancelled",
                name="booking_terminal_status_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("granted_fallback_index", sa.Integer(), nullable=True),
        sa.Column("response_payload", sa.Text(), nullable=True),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["operator_id"], ["operator_profile.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["rule_id"], ["scheduler_rule.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("booking_outcome", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_booking_outcome_operator_id"), ["operator_id"], unique=False
        )

    op.create_table(
        "class_preference",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("rule_id", sa.Integer(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("class_type", sa.String(length=100), nullable=False),
        sa.Column("target_time_slot", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(["rule_id"], ["scheduler_rule.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rule_id", "order_index", name="uq_class_preference_rule_order"),
    )
    with op.batch_alter_table("class_preference", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_class_preference_rule_id"), ["rule_id"], unique=False
        )

    op.create_table(
        "heartbeat_reading",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operator_id", sa.Integer(), nullable=False),
        sa.Column(
            "probed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "result",
            sa.Enum(
                "valid", "rejected", "unknown", name="heartbeat_result_enum", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("projected_ttl_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("alert_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["alert_id"], ["alert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["operator_id"], ["operator_profile.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("heartbeat_reading", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_heartbeat_reading_operator_id"), ["operator_id"], unique=False
        )


def downgrade() -> None:
    with op.batch_alter_table("heartbeat_reading", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_heartbeat_reading_operator_id"))
    op.drop_table("heartbeat_reading")

    with op.batch_alter_table("class_preference", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_class_preference_rule_id"))
    op.drop_table("class_preference")

    with op.batch_alter_table("booking_outcome", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_booking_outcome_operator_id"))
    op.drop_table("booking_outcome")

    with op.batch_alter_table("vacation_window", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vacation_window_operator_id"))
    op.drop_table("vacation_window")

    with op.batch_alter_table("scheduler_rule", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scheduler_rule_operator_id"))
    op.drop_table("scheduler_rule")

    with op.batch_alter_table("notification_outbox", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_outbox_operator_id"))
    op.drop_table("notification_outbox")

    with op.batch_alter_table("federated_identity", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_federated_identity_operator_id"))
    op.drop_table("federated_identity")

    op.drop_table("cookie_credential")

    with op.batch_alter_table("alert", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_alert_open_operator_kind", sqlite_where=sa.text("closed_at IS NULL")
        )
        batch_op.drop_index(batch_op.f("ix_alert_operator_id"))
    op.drop_table("alert")

    op.drop_table("operator_profile")
